# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 11:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('author', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('text', models.CharField(max_length=200)),
                ('user_mentions', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
                ('hashtags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
            ],
        ),
    ]
