# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tweet',
            table='tweet',
        ),
    ]
