# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 08:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20160408_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('profile_image_url', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
            ],
            options={
                'db_table': 'tweet_user',
            },
        ),
    ]
