# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_auto_20160413_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_count',
            field=models.IntegerField(default=int),
        ),
    ]
