# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_auto_20160419_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet.User'),
        ),
    ]
